[15.0] Add some departments fr oversea
OCA/l10n-france pull request #365
Opened 2022-06-08 08:20 UTC by DilawBz

We have added in this commit some departments of france oversea which were not included in your versions

2022-06-08 10:36 UTC, legalsylvain requested changes
Thanks for jour contribution. Some blocking points inline.
Regards.

2022-06-08 10:36 UTC, legalsylvain commented on l10n_fr_department_oversea/data/res_country_department.xml
> +    <!-- ### ADD AUNEOR-CONSEIL ### -->
Please remove the lines regarding auneor.

2022-06-08 10:36 UTC, legalsylvain commented on l10n_fr_department_oversea/data/res_country_department.xml
> +    <record id="res_country_department_monaco" model="res.country.department">
Monaco is a country.

2022-06-09 08:51 UTC, alexis-via commented
I disagree with this PR ; so far, res.country.department was for real French departments (DOMs) and not TOMs. I think we should not change that.

2022-06-09 08:54 UTC, alexis-via commented
So I propose to close this PR.

2022-11-13 12:44 UTC, closed without merging