[16.0][MIG] l10n_fr_department and l10n_fr_department_oversea
OCA/l10n-france pull request #399
Opened 2022-12-26 16:46 UTC by alexis-via

fix bug https://github.com/OCA/l10n-france/issues/384 : field department_id on res.partner has been renamed to country_department_id

2022-12-26 16:50 UTC, alexis-via commented
Requires https://github.com/OCA/l10n-france/pull/398

2022-12-26 18:17 UTC, legalsylvain requested changes
Thanks for porting this module. 

Migration script is missing.

Otherwise, LGTM.

2022-12-26 19:30 UTC, alexis-via commented
As it is a computed field, a migration script is not required, but it could save same time during migration.

2022-12-26 20:20 UTC, legalsylvain commented
> As it is a computed field, a migration script is not required, but it could save same time during migration.

Indeed. But a little weird to raise the recompute of an existing field. And on res.partner table, it can take time. Better to use rename_fields of openupgradelib.

2022-12-26 20:21 UTC, ivantodorovich commented on l10n_fr_department/model/res_partner.py
> +    # from https://github.com/OCA/partner-contact
These comments belong to the commit message or to the PR itself.

They're only useful when reviewing/analyzing changes from previous code.
But they have no use at all in the present/future code

2022-12-26 20:21 UTC, ivantodorovich commented on l10n_fr_department/view/res_country_department.xml
> +  Copyright 2013-2022 GRAP (http://www.grap.coop)
FTR you could save yourself from ever having to update these Copyright lines.
When reading the copyright comment, the dates are to be read as "starting.." (and legally it'll be valid for up to 70 years from that point)

eg: `Copyright 2013 GRAP (http://www.grap.coop)`

Means it's copyright is valid from 2013 to 2083.
There's no need at all to put an end date, that end up being just noisy diffs, and it's totally useless.


https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

2022-12-27 09:40 UTC, alexis-via commented
I added and tested the migration script. Requires a recent version of openupgradelib to support the new system for translations.

2022-12-27 10:13 UTC, legalsylvain approved these changes
Thanks !

2022-12-30 22:05 UTC, alexis-via commented
/ocabot merge nobump

2022-12-30 22:10 UTC, merged

2023-06-09 20:35 UTC, legalsylvain commented
/ocabot migration l10n_fr_department

2023-06-09 20:36 UTC, legalsylvain commented
/ocabot migration l10n_fr_department_oversea