[16.0][MIG] l10n_fr account invoice import modules
OCA/l10n-france pull request #430
Opened 2023-03-24 23:17 UTC by alexis-via

2023-03-25 04:03 UTC, legalsylvain approved these changes
Diff review / no test : lgtm.

Please take a look on red ci + red runboat.

Thanks !

2023-05-08 12:58 UTC, njeudy approved these changes
Ok I test a try to review code on V16 community and V16 enterprise :) Ok for me

2023-06-09 20:29 UTC, legalsylvain commented
/ocabot migration l10n_fr_account_invoice_import_facturx
/ocabot migration l10n_fr_account_invoice_import_simple_pdf
/ocabot migration l10n_fr_business_document_import

works for many modules ?

2023-06-09 20:30 UTC, legalsylvain commented
/ocabot migration l10n_fr_account_invoice_import_facturx

2023-10-08 14:13 UTC, legalsylvain commented
@alexis-via CI is red. could you take a look ? thanks.

2024-08-23 09:20 UTC, legalsylvain requested changes
CI still red. Could you take a look ?

2025-02-13 13:31 UTC, hparfr commented
Depends of https://github.com/OCA/edi/issues/803

2025-11-24 09:44 UTC, alexis-via commented
@legalsylvain Tests are now green, because the underlying modules are merged in OCA/edi. Could you update your "change request" ?

2025-11-24 11:00 UTC, legalsylvain reviewed
no review 

/ocabot merge nobump

2025-11-24 11:08 UTC, merged